### ISSUE TITLE
Create Showcase Sounds Component

### ISSUE THREAD

**Issue by Mervatabuamro** [HYF-Class20/Sound-Blog-Platform#20]
- [x]  This is developed on branch named 'Sound-List'
- [x]  Make all required codes
- [x] Give good explanation for commits
- [x] Make required styles
- [x] Assign yourself to this issue
- [x] Link right pull request to this issue
- [x] Assign at least two reviews to the pull request#
- [x] Put in the right project board list
- [x] Finish planned work within two weeks 

### Showcase Sounds JSX

- [x] A component below `Category`.
- [x] `Sounds` component will contain smaller individual `sound-component`.
- [x] There will be `navigation-buttons` similar to the category component.

### Showcase Sounds CSS

- [x] Make each individual sound line up vertically, and also need to be responsive.

**Comment by jialvaradob** [comment]
what kind of navigation buttons should this have?

**Comment by Ibrahim86Ali** [comment]
> what kind of navigation buttons should this have?

am not sure .... let me ask
