### ISSUE TITLE
Create Player Component

### ISSUE THREAD

**Issue by Mervatabuamro** [HYF-Class20/Sound-Blog-Platform#21]
- [x]  This is developed on branch named 'player'
- [x]  Make all required codes
- [x] Give good explanation for commits
- [x] Make required styles
- [x] Assign yourself to this issue
- [x] Link right pull request to this issue
- [x] Assign at least two reviews to the pull request#
- [x] Put in the right project board list
- [x] Finish planned work within two weeks 

### Player JSX

- [x] There should be a picture stick to the left with each sound that is randomly generated.
- [x] There should be the author and the name of the sound at right side of the picture.
- [x] This component will stick at the bottom of this website.
- [x] The player should contain a `play-button`, a `next-button` and a `previous-button`.
- [x] User should be able to see the `progress` of current sound.
- [ ] <span style="color:blue">Optional</span>: There could be an `volumn-button` to control volumns.

### Player CSS

- [x] responsive and will display a different picture when user switch to a different sound.

**Comment by jialvaradob** [comment]
Component not used in final version
